# Generated by Django 2.2.2 on 2019-06-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_medium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descprition', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('on_top_of', models.ManyToManyField(through='api.PizzaOrder', to='api.Pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(through='api.PizzaOrder', to='api.Topping'),
        ),
    ]
