# Generated by Django 2.2.2 on 2019-06-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='on_top_of',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaOrder',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
